# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FHNW/prj2/fhnw_zt/4_vivado/zt/zt.srcs/sources_1/bd/bd/ip/bd_lf_sampler_axi_master_0_2/bd_lf_sampler_axi_master_0_2.xci
# IP: The module: 'bd_lf_sampler_axi_master_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt/zt.gen/sources_1/bd/bd/constraints/Zybo-Z7-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_lf_sampler_axi_master_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/FHNW/prj2/fhnw_zt/4_vivado/zt/zt.srcs/sources_1/bd/bd/ip/bd_lf_sampler_axi_master_0_2/bd_lf_sampler_axi_master_0_2.xci
# IP: The module: 'bd_lf_sampler_axi_master_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt/zt.gen/sources_1/bd/bd/constraints/Zybo-Z7-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_lf_sampler_axi_master_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
