# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/FHNW/prj2/fhnw_zt/4_vivado/constraints/Zybo-Z7-Master.xdc

# Block Designs: bd/bd/bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd || ORIG_REF_NAME==bd} -quiet] -quiet

# IP: bd/bd/ip/bd_processing_system7_0_1/bd_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_processing_system7_0_1 || ORIG_REF_NAME==bd_processing_system7_0_1} -quiet] -quiet

# IP: bd/bd/ip/bd_proc_sys_reset_0_0/bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_proc_sys_reset_0_0 || ORIG_REF_NAME==bd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_dma_0_0/bd_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_dma_0_0 || ORIG_REF_NAME==bd_axi_dma_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_smartconnect_0_0/bd_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_smartconnect_0_0 || ORIG_REF_NAME==bd_smartconnect_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_lf_sampler_axi_maste_0_0/bd_lf_sampler_axi_maste_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_lf_sampler_axi_maste_0_0 || ORIG_REF_NAME==bd_lf_sampler_axi_maste_0_0} -quiet] -quiet

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt/zt.gen/sources_1/bd/bd/bd_ooc.xdc
