# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/FHNW/prj2/fhnw_zt/4_vivado/constraints/Zybo-Z7-Master.xdc

# Block Designs: bd/ZyboTank/ZyboTank.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboTank || ORIG_REF_NAME==ZyboTank} -quiet] -quiet

# IP: bd/ZyboTank/ip/ZyboTank_proc_sys_reset_0_0/ZyboTank_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboTank_proc_sys_reset_0_0 || ORIG_REF_NAME==ZyboTank_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ZyboTank/ip/ZyboTank_processing_system7_0_0/ZyboTank_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboTank_processing_system7_0_0 || ORIG_REF_NAME==ZyboTank_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZyboTank/ip/ZyboTank_axi_dma_1_0/ZyboTank_axi_dma_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboTank_axi_dma_1_0 || ORIG_REF_NAME==ZyboTank_axi_dma_1_0} -quiet] -quiet

# IP: bd/ZyboTank/ip/ZyboTank_ila_0_2/ZyboTank_ila_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboTank_ila_0_2 || ORIG_REF_NAME==ZyboTank_ila_0_2} -quiet] -quiet

# IP: bd/ZyboTank/ip/ZyboTank_ila_1_1/ZyboTank_ila_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboTank_ila_1_1 || ORIG_REF_NAME==ZyboTank_ila_1_1} -quiet] -quiet

# IP: bd/ZyboTank/ip/ZyboTank_lf_sampler_axi_maste_0_2/ZyboTank_lf_sampler_axi_maste_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboTank_lf_sampler_axi_maste_0_2 || ORIG_REF_NAME==ZyboTank_lf_sampler_axi_maste_0_2} -quiet] -quiet

# IP: bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/ZyboTank_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboTank_smartconnect_0_0 || ORIG_REF_NAME==ZyboTank_smartconnect_0_0} -quiet] -quiet

# Block Designs: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/bd_77ab.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_0/bd_77ab_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_1/bd_77ab_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_2/bd_77ab_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_3/bd_77ab_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_4/bd_77ab_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_5/bd_77ab_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_6/bd_77ab_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_7/bd_77ab_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_8/bd_77ab_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_9/bd_77ab_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_10/bd_77ab_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/ZyboTank/ip/ZyboTank_system_ila_0_1/ZyboTank_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZyboTank_system_ila_0_1 || ORIG_REF_NAME==ZyboTank_system_ila_0_1} -quiet] -quiet

# Block Designs: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_system_ila_0_1/bd_0/bd_22c6.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_22c6 || ORIG_REF_NAME==bd_22c6} -quiet] -quiet

# IP: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_system_ila_0_1/bd_0/ip/ip_0/bd_22c6_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_22c6_ila_lib_0 || ORIG_REF_NAME==bd_22c6_ila_lib_0} -quiet] -quiet

# IP: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_system_ila_0_1/bd_0/ip/ip_1/bd_22c6_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_22c6_g_inst_0 || ORIG_REF_NAME==bd_22c6_g_inst_0} -quiet] -quiet

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_proc_sys_reset_0_0/ZyboTank_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZyboTank_proc_sys_reset_0_0 || ORIG_REF_NAME==ZyboTank_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_proc_sys_reset_0_0/ZyboTank_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZyboTank_proc_sys_reset_0_0 || ORIG_REF_NAME==ZyboTank_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_processing_system7_0_0/ZyboTank_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZyboTank_processing_system7_0_0 || ORIG_REF_NAME==ZyboTank_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_axi_dma_1_0/ZyboTank_axi_dma_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZyboTank_axi_dma_1_0 || ORIG_REF_NAME==ZyboTank_axi_dma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_axi_dma_1_0/ZyboTank_axi_dma_1_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZyboTank_axi_dma_1_0 || ORIG_REF_NAME==ZyboTank_axi_dma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_ila_0_2/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZyboTank_ila_0_2 || ORIG_REF_NAME==ZyboTank_ila_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_ila_0_2/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZyboTank_ila_0_2 || ORIG_REF_NAME==ZyboTank_ila_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_ila_0_2/ZyboTank_ila_0_2_ooc.xdc

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_ila_1_1/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZyboTank_ila_1_1 || ORIG_REF_NAME==ZyboTank_ila_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_ila_1_1/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZyboTank_ila_1_1 || ORIG_REF_NAME==ZyboTank_ila_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_ila_1_1/ZyboTank_ila_1_1_ooc.xdc

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_1/bd_77ab_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_1/bd_77ab_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_5/bd_77ab_s00a2s_0_ooc.xdc

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_6/bd_77ab_sawn_0_ooc.xdc

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_7/bd_77ab_swn_0_ooc.xdc

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_8/bd_77ab_sbn_0_ooc.xdc

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/bd_0/ip/ip_9/bd_77ab_m00s2a_0_ooc.xdc

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_smartconnect_0_0/ooc.xdc

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_22c6_ila_lib_0 || ORIG_REF_NAME==bd_22c6_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_22c6_ila_lib_0 || ORIG_REF_NAME==bd_22c6_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_system_ila_0_1/bd_0/ip/ip_0/bd_22c6_ila_lib_0_ooc.xdc

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_system_ila_0_1/bd_0/bd_22c6_ooc.xdc

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ip/ZyboTank_system_ila_0_1/ZyboTank_system_ila_0_1_ooc.xdc

# XDC: c:/FHNW/prj2/fhnw_zt/4_vivado/zt_20240308/zt.gen/sources_1/bd/ZyboTank/ZyboTank_ooc.xdc
