
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_PERIPHERALS_DIMMER_GPIO_10_DEVICE_ID,
		XPAR_PERIPHERALS_DIMMER_GPIO_10_BASEADDR,
		XPAR_PERIPHERALS_DIMMER_GPIO_10_INTERRUPT_PRESENT,
		XPAR_PERIPHERALS_DIMMER_GPIO_10_IS_DUAL
	},
	{
		XPAR_PERIPHERALS_GPIO_DEVICE_ID,
		XPAR_PERIPHERALS_GPIO_BASEADDR,
		XPAR_PERIPHERALS_GPIO_INTERRUPT_PRESENT,
		XPAR_PERIPHERALS_GPIO_IS_DUAL
	}
};


